services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        #gitlab_rails['gitlab_shell_ssh_port'] = 2224
        # Security: Disable sign-ups for public instances
        gitlab_rails['signup_enabled'] = false
        # Enable container registry (optional)
        registry_external_url 'https://gitlab.example.com:5050'
        gitlab_rails['registry_enabled'] = true
        # Configure GitLab Pages (optional)
        pages_external_url nil
        gitlab_pages['enable'] = false
        # Email configuration (SMTP) - gmail
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "gitlab@example.com"
        gitlab_rails['smtp_password'] = "pwd"
        gitlab_rails['smtp_domain'] = "mg.example.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_from'] = 'gitlab@example.com'
        gitlab_rails['gitlab_email_display_name'] = 'GitLab Trendintown'
        gitlab_rails['gitlab_email_reply_to'] = 'info@example.com'
        # Backup configuration
        gitlab_rails['backup_keep_time'] = 604800
        # Performance tuning for smaller systems
        postgresql['shared_buffers'] = "256MB"
        postgresql['max_worker_processes'] = 8
        sidekiq['max_concurrency'] = 25
        # Additional security configurations
        nginx['ssl_protocols'] = "TLSv1.2 TLSv1.3"
        nginx['ssl_ciphers'] = "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384"
        nginx['ssl_prefer_server_ciphers'] = "on"
        nginx['ssl_session_cache'] = "builtin:1000 shared:SSL:10m"
        nginx['ssl_session_timeout'] = "5m"
        # Rate limiting
        gitlab_rails['rack_attack_git_basic_auth'] = {
          'enabled' => true,
          'ip_whitelist' => ["127.0.0.1"],
          'maxretry' => 10,
          'findtime' => 60,
          'bantime' => 3600
        }
        #Additional security settings
        gitlab_rails['gravatar_enabled'] = false
        gitlab_rails['default_projects_limit'] = 10
        gitlab_rails['default_can_create_group'] = false
        gitlab_rails['default_theme'] = 2
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
      - '5050:5050'  # Container registry port (optional)
    volumes:
      - /data/gitlab/config:/etc/gitlab
      - /data/gitlab/logs:/var/log/gitlab
      - /data/gitlab/data:/var/opt/gitlab
      - /etc/localtime:/etc/localtime:ro
    shm_size: '256m'
    # Resource limits (adjust based on your system)
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Optional: GitLab Runner for CI/CD
  gitlab-runner:
    image: gitlab/gitlab-runner:bleeding
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - /data/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  # Optional: Redis (if you want external Redis instead of built-in)
  # redis:
  #   image: redis:7.2-alpine
  #   container_name: gitlab-redis
  #   restart: always
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - /data/gitlab/redis:/data

  # Optional: PostgreSQL (if you want external DB instead of built-in)
  # postgresql:
  #   image: postgres:15.7-alpine
  #   container_name: gitlab-postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: gitlabhq_production
  #     POSTGRES_USER: gitlab
  #     POSTGRES_PASSWORD: gitlab_password
  #   volumes:
  #     - /data/gitlab/postgresql:/var/lib/postgresql/data

# volumes:
#   gitlab_config:
#     driver: local
#   gitlab_logs:
#     driver: local
#   gitlab_data:
#     driver: local
#   gitlab_runner_config:
#     driver: local
#   # gitlab_redis_data:
#   #   driver: local
#   # gitlab_postgresql_data:
#   #   driver: local

networks:
  default:
    name: gitlab_network
