version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        # Enable container registry (optional)
        registry_external_url 'http://gitlab.local:5050'
        gitlab_rails['registry_enabled'] = true
        # Configure GitLab Pages (optional)
        pages_external_url 'http://pages.local'
        gitlab_pages['enable'] = true
        # Email configuration (optional - configure as needed)
        gitlab_rails['smtp_enable'] = false
        # Backup configuration
        gitlab_rails['backup_keep_time'] = 604800
        # Performance tuning for smaller systems
        postgresql['shared_buffers'] = "256MB"
        postgresql['max_worker_processes'] = 8
        sidekiq['max_concurrency'] = 25
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
      - '5050:5050'  # Container registry port (optional)
    volumes:
      - /data/gitlab/config:/etc/gitlab
      - /data/gitlab/logs:/var/log/gitlab
      - /data/gitlab/data:/var/opt/gitlab
      - /etc/localtime:/etc/localtime:ro
    shm_size: '256m'
    # Resource limits (adjust based on your system)
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Optional: GitLab Runner for CI/CD
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - /data/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  # Optional: Redis (if you want external Redis instead of built-in)
  # redis:
  #   image: redis:7-alpine
  #   container_name: gitlab-redis
  #   restart: always
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - /data/gitlab/redis:/data

  # Optional: PostgreSQL (if you want external DB instead of built-in)
  # postgresql:
  #   image: postgres:15-alpine
  #   container_name: gitlab-postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: gitlabhq_production
  #     POSTGRES_USER: gitlab
  #     POSTGRES_PASSWORD: gitlab_password
  #   volumes:
  #     - /data/gitlab/postgresql:/var/lib/postgresql/data

# volumes:
#   gitlab_config:
#     driver: local
#   gitlab_logs:
#     driver: local
#   gitlab_data:
#     driver: local
#   gitlab_runner_config:
#     driver: local
#   # gitlab_redis_data:
#   #   driver: local
#   # gitlab_postgresql_data:
#   #   driver: local

networks:
  default:
    name: gitlab_network
